package mir.oslav.mockup.processor


/**
 * @since 1.0.0
 * @author Miroslav Hýbler <br>
 * created on 15.09.2023
 */
object MockupConstants {


    /**
     * File header comment attached on the top of every generated file
     * @since 1.0.0
     */
    const val GENERATED_FILE_HEADER: String = "" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////\n" +
            "/////                                                                                               \n" +
            "/////\t\tFile generated by Mockup Library                                                           \n" +
            "/////\t\tAuthor Miroslav Hýbler                                                                     \n"+
            "/////\t\tVersion: 2.0.0-ALPHA01                                                                             \n"+
            "/////                                                                                               \n" +
            "/////\t\tFor more information visit    https://github.com/miroslavhybler/ksp-mockup                 \n" +
            "/////\t\tFor report an issue visit     https://github.com/miroslavhybler/ksp-mockup/issues          \n" +
            "/////                                                                                               \n" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////"
}